#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenaxhimiKafiteris
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Kafiteria")]
	public partial class DbChartDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DbChartDataContext() : 
				base(global::MenaxhimiKafiteris.Properties.Settings.Default.KafiteriaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbChartDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbChartDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbChartDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbChartDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<view_KamarieratDheTotalin> view_KamarieratDheTotalins
		{
			get
			{
				return this.GetTable<view_KamarieratDheTotalin>();
			}
		}
		
		public System.Data.Linq.Table<view_ShitjetPerTavoline> view_ShitjetPerTavolines
		{
			get
			{
				return this.GetTable<view_ShitjetPerTavoline>();
			}
		}
		
		public System.Data.Linq.Table<view_topKategoriteMeShitje> view_topKategoriteMeShitjes
		{
			get
			{
				return this.GetTable<view_topKategoriteMeShitje>();
			}
		}
		
		public System.Data.Linq.Table<view_TotalOrdersLast7Day> view_TotalOrdersLast7Days
		{
			get
			{
				return this.GetTable<view_TotalOrdersLast7Day>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_KamarieratDheTotalin")]
	public partial class view_KamarieratDheTotalin
	{
		
		private System.Nullable<decimal> _Totali;
		
		private string _Kamarieri;
		
		public view_KamarieratDheTotalin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Totali", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Totali
		{
			get
			{
				return this._Totali;
			}
			set
			{
				if ((this._Totali != value))
				{
					this._Totali = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kamarieri", DbType="VarChar(50)")]
		public string Kamarieri
		{
			get
			{
				return this._Kamarieri;
			}
			set
			{
				if ((this._Kamarieri != value))
				{
					this._Kamarieri = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_ShitjetPerTavoline")]
	public partial class view_ShitjetPerTavoline
	{
		
		private System.Nullable<decimal> _Totali;
		
		private System.Nullable<int> _TavolinaID;
		
		public view_ShitjetPerTavoline()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Totali", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Totali
		{
			get
			{
				return this._Totali;
			}
			set
			{
				if ((this._Totali != value))
				{
					this._Totali = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TavolinaID", DbType="Int")]
		public System.Nullable<int> TavolinaID
		{
			get
			{
				return this._TavolinaID;
			}
			set
			{
				if ((this._TavolinaID != value))
				{
					this._TavolinaID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_topKategoriteMeShitje")]
	public partial class view_topKategoriteMeShitje
	{
		
		private System.Nullable<int> _sasia;
		
		private string _Lloji;
		
		public view_topKategoriteMeShitje()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sasia", DbType="Int")]
		public System.Nullable<int> sasia
		{
			get
			{
				return this._sasia;
			}
			set
			{
				if ((this._sasia != value))
				{
					this._sasia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lloji", DbType="VarChar(50)")]
		public string Lloji
		{
			get
			{
				return this._Lloji;
			}
			set
			{
				if ((this._Lloji != value))
				{
					this._Lloji = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_TotalOrdersLast7Days")]
	public partial class view_TotalOrdersLast7Day
	{
		
		private System.Nullable<int> _nr_Porosive;
		
		private System.Nullable<int> _DayofYear_OrderDate;
		
		public view_TotalOrdersLast7Day()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_Porosive", DbType="Int")]
		public System.Nullable<int> nr_Porosive
		{
			get
			{
				return this._nr_Porosive;
			}
			set
			{
				if ((this._nr_Porosive != value))
				{
					this._nr_Porosive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayofYear_OrderDate", DbType="Int")]
		public System.Nullable<int> DayofYear_OrderDate
		{
			get
			{
				return this._DayofYear_OrderDate;
			}
			set
			{
				if ((this._DayofYear_OrderDate != value))
				{
					this._DayofYear_OrderDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
